### ISSUE TITLE
example

### ISSUE THREAD

**Issue by llSourcell** [adambcomer/Tensorflow-Seq2Seq-Dialogs#1]
hey can you please show an example of a command line argument for your code for train.py?

**Comment by adambcomer** [comment]
Do you happen to run the youtube channel Sirajology? If you do, I watch your videos on youtube all the time. 

To use this TensorFlow model you need 2 things a training set in the form of csv file where the dialog pairs are separated by a comma and train.py. The training dataset should not have any commas in the data. Before TensorFlow builds the model we compile a dictionary of all the words in the training set to convert them to vectors. The code has a word frequency minimum by default, but you can uncomment one line to use every word in the dataset. The function is create_dictionary() near the bottom if you wish to do so.

Example data:
_hi,hello
how are you?,i'm well
what is your name?,my name is john_

Once the dictionary is built(This can take a few hours!) TensorFlow makes the model and starts training.  

## train.py
`python train.py -dialog_path -units -layers -training_iterations -batch_size --restore --display_out --load_dictionary`

Required to build:
- dialog_path: path to the dialog csv ex: /user/dialog_folder/
- units: number of neurons per GRU cell
- layers: number of layers deep for the recurrent model (min. 1)
- training_iteration: number of mini-batches to train on
- batch_size: number of dialog pairs per mini-batch

Not required:
- --restore: restores the model from a past save
- --display_out: displays a feed-forward of the model to the console
- --load_dictionary: uses a pre-built dictionary. Use this once you have built the model at least once. It save computing time.

All of the **Not Required** args are booleans that are entered automatically.

Example:
`python train.py ~/adam/tensorflow_seq2seq/ 512 4 1000000 32`
Makes a new model where the data is at "~/adam/tensorflow_seq2seq/". The model has 512 neurons per GRU cell and is 4 layers deep. The program will run for 1,000,000 iterations with a batch size of 32. 

`python train.py ~/adam/tensorflow_seq2seq/ 512 4 1000000 32 --restore --display_out --load_dictionary`
This command will build the same model above and restore from a past save. This command will display a feed-forward pass after each training iteration. Also this command will use a past dictionary that is generated after the first run of the model. 

## test.py
`python test.py -dialog_path -units -layers`

Required to build:
- dialog_path: use the same path as used to train the model
- units: use the same number of neurons as when training
- layers: use the same number of layers as when training

Example:
`python train.py ~/adam/tensorflow_seq2seq/ 512 4`
This will use the model above after training. Once you run this a "> " will appear. Type in anything you want to see the output of the model. 


## Example:

Visit this webpage to see a working version. [https://www.facebook.com/adamsbot/](https://www.facebook.com/adamsbot/)
Just send it a message. This example was trained for 2 weeks on a GTX 1060 and is only half baked. Answers can be repetitive.  

FYI: To train this model you need something like a GTX TITAN X or a cluster computer and a lot of time. Not for the Deep Learning weary.
